development:
  adapter: postgresql
  encoding: unicode
  database: sconline
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sconline_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sconline
  pool: 5
  username: postgres
  password:
